language: ruby
rvm:
  - 2.4.1
services:
  - postgresql

bundler_args: "--without development --deployment"

cache: bundler

before_script:
  - cp config/database.travis.yml config/database.yml
  - bundle exec rails db:setup

script:
  - bundle exec rails test